## Imports and Functions

#### The code in the file ML.py is modified from material for Rayid Ghani's Spring 2018 ML for Public Policy course.

In [1]:
from data_functions import *
from ML import *

import warnings
warnings.filterwarnings('ignore')

In [2]:
def temporal_train_test_data_split(df, features, filter_var, outcome_var):
    start_date = '2004'
    training_end_date = '2008'
    testing_end_date = '2010'

    y_df = df[[filter_var, outcome_var]]

    x_train_filter_by_date = filter_df_by_date_range(df, filter_var, training_end_date, testing_end_date)
    x_test_filter_by_date = filter_df_by_date_range(df, filter_var, start_date, training_end_date)

    y_train_filter_by_date = filter_df_by_date_range(y_df, filter_var, training_end_date, testing_end_date)
    y_test_filter_by_date = filter_df_by_date_range(y_df, filter_var, start_date, training_end_date)

    x_train = x_train_filter_by_date[features]
    x_test = x_test_filter_by_date[features]

    y_train = y_train_filter_by_date[outcome_var]
    y_test = y_test_filter_by_date[outcome_var]

    return x_test, x_train, y_test, y_train

In [3]:
def single_year(df, year):
    
    voting_cols = ['voted2004','voted2006', 'voted2008', 'voted2010']
    common = ['county', 'name', 'city', 'zip', 'address', 'phone', 'gender', 'age',
       'precinct', 'cong_dist', 'nc_senate', 'nc_house', 'idx', 'white',
       'black', 'hispanic', 'dem', 'rep']

    df['election_year'] = year
    col_name = "voted" + year
    voting_cols.remove(col_name)
    df = df[common + ['election_year'] + [col_name]]
    df.columns = common + ['election_year'] + ['voted']

    return df

### Open and reformat data

In [4]:
data = read('voterfileNC.dta')
data = data.rename(index=str, columns={"id": "idx"})
data.columns

Index(['county', 'name', 'city', 'zip', 'address', 'phone', 'gender', 'age',
       'precinct', 'cong_dist', 'nc_senate', 'nc_house', 'idx', 'white',
       'black', 'hispanic', 'dem', 'rep', 'regyear', 'voted2004', 'voted2006',
       'voted2008', 'voted2010'],
      dtype='object')

### Reshape the data to “long” format such that each row pertains to an individual in a given election year.

In [5]:
v04, v06, v08, v10 = data.copy(), data.copy(), data.copy(), data.copy()

In [6]:
v04_only = single_year(v04, '2004')
v06_only = single_year(v06, '2006')
v08_only = single_year(v08, '2008')
v10_only = single_year(v10, '2010')

In [7]:
frames = [v04_only, v06_only, v08_only, v10_only]
long = pd.concat(frames)

In [8]:
l = long.copy()
l.shape

(40000, 20)

## Part 1: Predict likely voters

### Briefly discuss relevant predictors in the voter file (voterfileNC.dta)

Factors that can be predictive of turnout include race (white, black), ethnicity (hispanic), gender, and age. Young people in particular generally have low turnout rates. Their address or location could be influential as well, but that would likely be due to and reflected in other factors.

#### Add columns that could be useful.

In [9]:
l['is_midterm'] = l.election_year.apply(lambda x: 1 if (int(x) % 4 == 0) else 1)
l['gender'] = l.gender.apply(lambda x: 1 if x == 'F' else 0)

In [10]:
l.head().style

In [11]:
l.columns

Index(['county', 'name', 'city', 'zip', 'address', 'phone', 'gender', 'age',
       'precinct', 'cong_dist', 'nc_senate', 'nc_house', 'idx', 'white',
       'black', 'hispanic', 'dem', 'rep', 'election_year', 'voted',
       'is_midterm'],
      dtype='object')

#### I narrowed down the features so that I did not double count any of the characteristiscs like white vs. black or rep vs. dem.

In [12]:
rfeats = ['gender', 'white', 'hispanic', 'rep', 'is_midterm', 'age']

In [13]:
x_train, x_test, y_train, y_test  = temporal_train_test_data_split(l, rfeats , 'election_year', 'voted')

### Models

In [14]:
results_df = run_simple_loop(x_train, x_test, y_train, y_test, 'small')

DT
KNN
LR

### Test their predictive performance.

In [15]:
results_df = results_df[['model_type', 'clf', 'parameters', 'baseline_p', 'auc-roc', 'p_at_10', 'r_at_10', 'f1_at_10']]

In [16]:
results_df.to_pickle('results_df.pkl')
results_df = pd.read_pickle('results_df.pkl')

#### I decided to use the metric of precision at 10% to select voters to target. We are looking for 1000-2000 candidates out of 10,000 potential voters, so 10%. I also decided that being able to correctly identify a potential voter, precision, was more important than classifying all voters correctly. Knowing which models had the highest precision would be more helpful in making predictions for the future.  I looked at a total of 98 models: 36 decision trees, 36 K-nearest neighbors, and 10 logistic regressions.

In [17]:
dt_results = results_df[results_df.model_type == 'DT']
knn_results = results_df[results_df.model_type == 'KNN']
lr_results = results_df[results_df.model_type == 'LR']

print("Best Decision Tree")
print(find_best_model(dt_results, criteria='p_at_10'))
print("\n" + "Best K Nearest Neighbor")
print(find_best_model(knn_results, criteria='p_at_10'))
print("\n" + "Best Logistoic Regression")
print(find_best_model(lr_results, criteria='p_at_10'))

Best Decision Tree
DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=100,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

Best K Nearest Neighbor
KNeighborsClassifier(algorithm='kd_tree', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=100, p=2,
           weights='distance')

Best Logistoic Regression
LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
best_clf = find_best_model(results_df, criteria='p_at_10')
best_clf

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=100,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

### Rank the voters by their predicted propensity to vote

In [19]:
thresh, topN = 0.5, 5000

final,ids, cnt = [], [], 0
y_scores = best_clf.predict_proba(x_test)[:,1]
dfinal = x_test.copy()
dfinal['label_value'] = y_test
dfinal['scores'] = y_scores
dfinal['score'] = np.where(dfinal['scores'] > thresh, 1, 0)

dfinal = dfinal.sort_values(by='scores', ascending=False)
df_id = l[['idx']]
dF = pd.merge(df_id, dfinal, left_index=True, right_index=True)
dF = dF.sort_values(by='scores', ascending=False)
mini= dF[['idx', 'scores', 'score']]

top_lst = [tuple(x) for x in mini.values]

for idx, scores, score in top_lst:
    if idx not in ids and cnt <=topN-1:
        ids.append(idx)
        final.append(idx)
        cnt +=1

In [20]:
s = pd.DataFrame()
s['idx'] = final

In [21]:
demo = l[['idx', 'name', 'county', 'city', 'zip', 'address', 'phone', 'gender', 'age', 'white', 'black', 'hispanic', 'dem']]
demo = demo.drop_duplicates()

In [22]:
s = s.merge(demo, on=['idx'], how='left')

#### Remove Republicans to make sure you have 2000 potential democratic voters.

In [23]:
dem_potentials = s[s.dem == 1.0][:2000]
dem_potentials.shape

(2000, 13)

### Make a list of the 1,000 people your door-to-door campaign should contact.

#### In order to minimize logistics issues, I decided to select the 1000 voters who lived in more similar areas for door to door contact. I counted how many people lived in each of the counties, and selected the 16 where the most likely voters lived.

In [24]:
county_size = dem_potentials.county.value_counts()
counties = []

n = 0
for idx, val in county_size.iteritems():
    if n < 1000:
        print(idx, val)
        n += val
        counties.append(idx)

BUNCOMBE 150
NEW HANOVER 68
JOHNSTON 67
CUMBERLAND 66
CRAVEN 60
HARNETT 57
ROCKINGHAM 55
LENOIR 55
SURRY 52
HAYWOOD 49
CABARRUS 48
RUTHERFORD 46
HENDERSON 46
WILSON 46
WAYNE 46
BRUNSWICK 44
SAMPSON 41
CHATHAM 41

In [25]:
dem_potentials['gender'] = dem_potentials.gender.apply(lambda x: 'F' if x == 1 else 'M')

In [26]:
door = dem_potentials[dem_potentials.county.isin(counties)][:1000]
door.to_csv('PS4_door_to_door.csv')

### Make another list of the 1,000 people you would like to reach via direct mail.

In [27]:
letters = dem_potentials[~dem_potentials.isin(door)].dropna()
letters.to_csv('PS4_by_direct_mail.csv')

## Part 2: Produce Content

### Describe how you would like to implement the door-to-door campaign: What is the message, who is the messenger etc.

#### This list is sorted by city so that volunteers from each city can focus on the people they need to target.

In [28]:
door.sort_values(by=['city', 'black'])

,idx,name,county,city,zip,address,phone,gender,age,white,black,hispanic,dem
2101,AL207727,LUCY LORRAINE ROBERTSON,BUNCOMBE,ALEXANDER,28701,15 DONNA LN,828 484 9041,F,84,1.0,0.0,0.0,1.0
340,CJ113299,BETTY KING POOLE,JOHNSTON,ANGIER,27501,1625 MASSENGILL POND RD,919 639 6185,F,80,1.0,0.0,0.0,1.0
948,CA48278,PHYLLIS WOOD COZART,HARNETT,ANGIER,27501,115 HONEYCUTT DR #D,910 892 7040,F,62,1.0,0.0,0.0,1.0
1404,CA19263,RICHARD LEROY WELLS JR,HARNETT,ANGIER,27501,441 WELLS LN,919 639 4389,M,61,1.0,0.0,0.0,1.0
1681,CA91724,THERESA DEAN WILKINS,HARNETT,ANGIER,27501,2563 OAK GROVE CHURCH RD,919 639 4847,F,53,1.0,0.0,0.0,1.0
3219,CJ84411,ETHEL ROSE JOHNSON,JOHNSTON,ANGIER,27501,105 PLEASANT PINE DR,919 331 8085,F,66,1.0,0.0,0.0,1.0
3547,CA15102,BESSIE S PRUETT,HARNETT,ANGIER,27501,9767 NC 210 N,919 639 2284,F,88,1.0,0.0,0.0,1.0
3743,CA19055,EIRA TAYLOR WATKINS,HARNETT,ANGIER,27501,372 N BROAD ST E,919 639 4588,F,88,1.0,0.0,0.0,1.0
4615,CA82506,PAMELA TALLEY,HARNETT,ANGIER,27501,321 MANGUM RD,919 639 8167,F,49,1.0,0.0,0.0,1.0
378,AX25605,LAURIER ROSS BUSH,CHATHAM,APEX,27523,107 SHADY LANE CIR,919 828 6260,M,71,1.0,0.0,0.0,1.0
672,AX19148,JESSE RAYMOND CARROLL,CHATHAM,APEX,27523,2071 HOLLANDS CHAPEL RD,919 632 6394,M,75,1.0,0.0,0.0,1.0
165,EB53451,JEROME NEMZOFF,SURRY,ARARAT,27007,103 SIMMONS FARM LN,336 374 7373,M,77,1.0,0.0,0.0,1.0
2767,EB47598,RICHARD ELGIN BRYANT,SURRY,ARARAT,27007,3580 ARARAT RD,336 374 5345,M,70,1.0,0.0,0.0,1.0
4384,EB21948,JEFFERSON COOPER DRAUGHON,SURRY,ARARAT,27007,984 LITTLE MOUNTAIN CH RD,336 374 2092,M,62,1.0,0.0,0.0,1.0
353,AL142698,HILDEGARD BUTLER,BUNCOMBE,ARDEN,28704,300 LONG SHOALS RD #4C,828 681 8134,F,80,1.0,0.0,0.0,1.0
1239,BE36537,WALTER BULLOCK PARIS,BUNCOMBE,ARDEN,28704,7 BRAMBLE CT,828 676 0059,M,68,1.0,0.0,0.0,1.0
2390,AL151743,PAUL JOSEPH TULEY,BUNCOMBE,ARDEN,28704,304 ROXBURY PL,828 684 4010,M,51,1.0,0.0,0.0,1.0
2735,AL79366,CHARLES J YODER,BUNCOMBE,ARDEN,28704,7 TURNBERRY DR,828 253 8670,M,70,1.0,0.0,0.0,1.0
2947,AL155838,BRENDA KAY LEWIS,BUNCOMBE,ARDEN,28704,48 LINDEN ST,828 681 9840,F,46,1.0,0.0,0.0,1.0
3026,AL118267,ALEC ANDREW FEHL,BUNCOMBE,ARDEN,28704,40 RHODODENDRON DR,828 236 3836,M,45,1.0,0.0,0.0,1.0
3286,AL216191,MARTHA CAROL LIVESAY,BUNCOMBE,ARDEN,28704,24 AVERY CREEK RD,828 687 9866,F,60,1.0,0.0,0.0,1.0
3348,CC47726,BRENDA PRAYTOR LEWIS,HENDERSON,ARDEN,28704,0 BAGWELL MILL RD,828 684 8870,F,59,1.0,0.0,0.0,1.0
3576,AL94113,DAVID PIERCE BRADLEY,BUNCOMBE,ARDEN,28704,45 MOUNTAIN VIEW DR,828 687 4468,M,57,1.0,0.0,0.0,1.0
419,AK34972,GENEVIEVE LETOURNEAU-HUGHES,BRUNSWICK,ASH,28420,7027 HUGHES-SMITH RD NW,910 287 3757,F,79,1.0,0.0,0.0,1.0
161,AL11869,WADE GORRELL HAMPTON JR,BUNCOMBE,ASHEVILLE,28805,22 CHATEAU PL,828 254 4202,M,83,1.0,0.0,0.0,1.0
217,AL8889,JIM MARTEL EAKER,BUNCOMBE,ASHEVILLE,28804,8 E BAIRD MOUNTAIN RD,828 645 7066,M,76,1.0,0.0,0.0,1.0
278,AL6250,WILLIAM J CARTER,BUNCOMBE,ASHEVILLE,28804,141 MACEDONIA RD,828 253 2002,M,80,1.0,0.0,0.0,1.0
344,AL24330,ALICE WILDE SLUDER,BUNCOMBE,ASHEVILLE,28806,731 NEW LEICESTER HWY,828 258 1373,F,80,1.0,0.0,0.0,1.0
588,AL12763,TONY ANTHONY HENSLEY,BUNCOMBE,ASHEVILLE,28806,39 DELAWARE AVE,828 254 4250,M,79,1.0,0.0,0.0,1.0
602,AL30598,ROGER WILLIAM BISSINGER,BUNCOMBE,ASHEVILLE,28806,30 FIELDCREST CIR,828 255 8606,M,79,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2348,EP74508,LUCILLE BLACKWELL GLOVER,WILSON,WILSON,27896,5655 HORNES CHURCH RD,252 243 6513,F,51,1.0,0.0,0.0,1.0
3020,EP23566,TIMOTHY ALLEN LAMM,WILSON,WILSON,27893,1802 LYNN DR,252 246 9774,M,45,1.0,0.0,0.0,1.0
3343,EP7942,WANDA JO ETHERIDGE,WILSON,WILSON,27896,1111 TREEMONT RD,252 399 7986,F,55,1.0,0.0,0.0,1.0
3554,EP23655,CLAYTON SCOVILL SAUNDERS,WILSON,WILSON,27893,505 PIKE ST,252 237 6311,M,89,1.0,0.0,0.0,1.0
3697,EP43158,PHYLLIS BAILEY WEBB,WILSON,WILSON,27893,4313 TARTTS MILL RD,252 237 3138,F,64,1.0,0.0,0.0,1.0
3846,EP37148,SANDRA ALLEN RUFFIN,WILSON,WILSON,27896,3303 CHRISTOPHER DR #APT-A,252 281 5397,F,61,1.0,0.0,0.0,1.0
3852,EP24400,JAMES WYATT O'NEAL,WILSON,WILSON,27896,1116 WINDEMERE DR,252 291 8204,M,59,1.0,0.0,0.0,1.0
4397,EP20676,JOSEPH KIMREY TURNER,WILSON,WILSON,27896,1221 BUXTON RD,252 237 7478,M,62,1.0,0.0,0.0,1.0
4450,EP65372,LINDA BARNES REBOLLAR,WILSON,WILSON,27896,4314 CAM STRADER DR,252 237 0237,F,54,1.0,0.0,0.0,1.0
118,EP16317,DAZELL BATTS PEARSON,WILSON,WILSON,27893,1305 QUEEN ST,252 243 5501,F,79,0.0,1.0,0.0,1.0
329,EP14455,MARY DEANS MCLAURIN,WILSON,WILSON,27893,414 VICK ST E,252 237 6009,F,87,0.0,1.0,0.0,1.0
1014,EP77661,MARY JANETTE MELTON,WILSON,WILSON,27893,5541 SCUPPERNONG RD,252 307 0016,F,64,0.0,1.0,0.0,1.0
1279,EP51915,CHRISTINE DELORIS DEANS,WILSON,WILSON,27893,223 SPRUCE ST SW,252 243 0381,F,68,0.0,1.0,0.0,1.0
2224,EP33673,RUTH ARTIS SMITH,WILSON,WILSON,27893,804 VIOLA ST,252 243 3759,F,76,0.0,1.0,0.0,1.0
2263,EP21415,CAROLYN GRAY JONES,WILSON,WILSON,27893,205 FAIRVIEW AVE,252 291 6582,F,59,0.0,1.0,0.0,1.0
2711,EP45007,INEZ MOORE,WILSON,WILSON,27893,119 GARNER ST W,252 399 0434,F,67,0.0,1.0,0.0,1.0
2838,BX13342,PAMALA EDWARDS FRIESON,WILSON,WILSON,27896,1704 LAKESIDE DR NW,252 206 6610,F,41,0.0,1.0,0.0,1.0
2839,EP33960,ANTONIA MARIE COLLINS,WILSON,WILSON,27893,1118 CRAWFORD ST S,252 237 5633,F,41,0.0,1.0,0.0,1.0
3539,EP19860,WILLIE RANDOLPH SUTTON,WILSON,WILSON,27896,2612 WILLIS CT,252 243 0808,M,59,0.0,1.0,0.0,1.0
3562,EP27980,DEBORAH GAIL SHERROD,WILSON,WILSON,27893,5708 WOODSIDE RD,252 236 4576,F,58,0.0,1.0,0.0,1.0
4023,EP8247,MARY RAY BARNES,WILSON,WILSON,27893,2124 SILVERLEAF RD,252 237 1280,F,60,0.0,1.0,0.0,1.0
4040,EP35704,JANICE FAYE ALLEN,WILSON,WILSON,27893,504 DEWEY ST SW,252 243 5403,F,60,0.0,1.0,0.0,1.0
4192,EP62059,LUCILLE VIRGINIA LIGGINS,WILSON,WILSON,27893,1815 NASH ST NW,252 246 0429,F,65,0.0,1.0,0.0,1.0
4210,EP35173,JAMES HEDERICK MILLS,WILSON,WILSON,27893,911 MEADOW ST,252 399 7639,M,60,0.0,1.0,0.0,1.0
4329,EP83131,LIONEL LEWIS,WILSON,WILSON,27893,1707 WESTWOOD AVE,252 230 3729,M,61,0.0,1.0,0.0,1.0
4616,EP41179,ROBERT J JONES,WILSON,WILSON,27893,211 KENAN ST W #APT-128,252 243 9858,M,69,0.0,1.0,0.0,1.0
358,AK85843,GAIL TRAISTER GIBSON,BRUNSWICK,WINNABOW,28479,735 BEACHWALK DR,910 371 1460,F,72,1.0,0.0,0.0,1.0
2350,AK73402,PATSY RYALS PALLAS,BRUNSWICK,WINNABOW,28479,1405 CHERRYTREE RD NE,910 253 0034,F,51,1.0,0.0,0.0,1.0
1827,CJ125695,RANDY LEE ONEAL,JOHNSTON,ZEBULON,27597,661 OLD EASON RD,919 815 6806,M,58,1.0,0.0,0.0,1.0
3396,CJ17082,JENNY PHILLIPS CREECH,JOHNSTON,ZEBULON,27597,13071 NC 39 HWY,919 269 6315,F,59,1.0,0.0,0.0,1.0

In [29]:
door.gender.value_counts()

F    625
M    375
Name: gender, dtype: int64

In [30]:
door.age.describe()

count    1000.000000
mean       66.056000
std        11.689633
min        36.000000
25%        58.000000
50%        65.000000
75%        74.000000
max       103.000000
Name: age, dtype: float64

In [31]:
"white", door.white.mean(), "black", door.black.mean(), "hispanic", door.hispanic.mean(),

('white', 0.815, 'black', 0.174, 'hispanic', 0.003)

In [32]:
door[(door.white == 1) & (door.gender == 'F')].shape

(501, 13)

In [33]:
black_door = door[door.black == 1]
black_door.city.value_counts()[:5]

FAYETTEVILLE    20
WILSON          17
KINSTON         15
REIDSVILLE      11
GOLDSBORO       10
Name: city, dtype: int64

In [34]:
black_door.gender.value_counts()

F    117
M     57
Name: gender, dtype: int64

### Describe how you would like to implement the direct mail campaign: Write the letter you would like to be distributed.

In [35]:
"white", letters.white.mean(), "black", letters.black.mean(), "hispanic", letters.hispanic.mean(),

('white', 0.764, 'black', 0.217, 'hispanic', 0.002)

In [36]:
letters.gender.value_counts()

F    628
M    372
Name: gender, dtype: int64

In [37]:
letters[letters.duplicated(keep=False)]

Empty DataFrame
Columns: [idx, name, county, city, zip, address, phone, gender, age, white, black, hispanic, dem]
Index: []

In [38]:
letters.iloc[0]

idx                     CZ10393
name           ROBERT T VEASEY
county                    MOORE
city                   ABERDEEN
zip                       28315
address     110  CAMPBELL ST
phone              910 944 1666
gender                        M
age                          91
white                         1
black                         0
hispanic                      0
dem                           1
Name: 23, dtype: object

In [39]:
l[l.name == 'LEE E HINTON ']

,county,name,city,zip,address,phone,gender,age,precinct,cong_dist,...,nc_house,idx,white,black,hispanic,dem,rep,election_year,voted,is_midterm
1170,JOHNSTON,LEE E HINTON,SMITHFIELD,27577,410 E HOLT ST,919 934 7925,0,46,PR26,7.0,...,28.0,CJ90250,0.0,1.0,0.0,1.0,0.0,2004,1.0,1
1170,JOHNSTON,LEE E HINTON,SMITHFIELD,27577,410 E HOLT ST,919 934 7925,0,46,PR26,7.0,...,28.0,CJ90250,0.0,1.0,0.0,1.0,0.0,2006,0.0,1
1170,JOHNSTON,LEE E HINTON,SMITHFIELD,27577,410 E HOLT ST,919 934 7925,0,46,PR26,7.0,...,28.0,CJ90250,0.0,1.0,0.0,1.0,0.0,2008,0.0,1
1170,JOHNSTON,LEE E HINTON,SMITHFIELD,27577,410 E HOLT ST,919 934 7925,0,46,PR26,7.0,...,28.0,CJ90250,0.0,1.0,0.0,1.0,0.0,2010,0.0,1